---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    eigr_functions_protocol_major_version: "0"
    eigr_functions_protocol_minor_version: "1"
    proxy_name: spawn
    k8s-app: spawn-proxy
  name: spawn-proxy
  namespace: eigr-functions
spec:
  replicas: 1
  selector:
    matchLabels:
      eigr_functions_protocol_major_version: "0"
      eigr_functions_protocol_minor_version: "1"
      proxy_name: spawn
      k8s-app: spawn-proxy
  template:
    metadata:
      labels:
        eigr_functions_protocol_major_version: "0"
        eigr_functions_protocol_minor_version: "1"
        proxy_name: spawn
        k8s-app: spawn-proxy
    spec:
      containers:
        - env:
            - name: MIX_ENV
              value: prod
            - name: BONNY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: BONNY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: BONNY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: BONNY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          image: eigr/spawn-proxy:0.1.0
          name: spawn-proxy
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 65534
