title: Spawn
description: >- # Markdown support is enabled
  A Actor based Service Mesh runtime.

# Build settings
markdown: kramdown
remote_theme: pages-themes/slate@v0.2.0

# Custom CSS
sass:
  style: compressed

# Add links to your custom CSS
#include:
#  - /assets/css/style.css

plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
