title: Spawn
description: >- # Markdown support is enabled
  A Actor based Service Mesh runtime.

# Build settings
markdown: kramdown
theme: slate # Default theme, or you can specify another one

# Custom CSS
sass:
  style: compressed

# Add links to your custom CSS
include:
  - /assets/css/style.css
