---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    eigr_functions_protocol_major_version: '0'
    eigr_functions_protocol_minor_version: '1'
    proxy_name: spawn
    k8s-app: eigr-functions-controller
  name: eigr-functions-controller
  namespace: eigr-functions
spec:
  replicas: 1
  selector:
    matchLabels:
      eigr_functions_protocol_major_version: '0'
      eigr_functions_protocol_minor_version: '1'
      proxy_name: spawn
      k8s-app: eigr-functions-controller
  template:
    metadata:
      labels:
        eigr_functions_protocol_major_version: '0'
        eigr_functions_protocol_minor_version: '1'
        proxy_name: spawn
        k8s-app: eigr-functions-controller
    spec:
      containers:
        - env:
            - name: MIX_ENV
              value: prod
            - name: BONNY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: BONNY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: BONNY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: BONNY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          image: eigr/spawn-operator:0.1.0
          name: eigr-functions-controller
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
      serviceAccountName: eigr-functions

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    eigr_functions_protocol_major_version: '0'
    eigr_functions_protocol_minor_version: '1'
    proxy_name: spawn
    k8s-app: eigr-functions-controller
  name: activators.spawn.eigr.io
spec:
  group: spawn.eigr.io
  names:
    kind: Activator
    plural: activators
    shortNames:
      - act
      - acts
      - activator
      - activators
    singular: activator
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - description: Activator Type
          jsonPath: .spec.activator.type
          name: type
          type: string
        - description: Method used to expose Activator
          jsonPath: .spec.activator.expose.method
          name: external
          type: string
        - description: |-
            CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.
            
                  Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
          jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    eigr_functions_protocol_major_version: '0'
    eigr_functions_protocol_minor_version: '1'
    proxy_name: spawn
    k8s-app: eigr-functions-controller
  name: actornodes.spawn.eigr.io
spec:
  group: spawn.eigr.io
  names:
    kind: ActorNode
    plural: actornodes
    shortNames:
      - ac
      - actor
      - actors
      - actornode
      - actornodes
    singular: actornode
  scope: Cluster
  versions:
    - additionalPrinterColumns: []
      name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    eigr_functions_protocol_major_version: '0'
    eigr_functions_protocol_minor_version: '1'
    proxy_name: spawn
    k8s-app: eigr-functions-controller
  name: actorsystems.spawn.eigr.io
spec:
  group: spawn.eigr.io
  names:
    kind: ActorSystem
    plural: actorsystems
    shortNames:
      - as
      - actorsys
      - actorsystem
      - actorsystems
      - system
    singular: actorsystem
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - description: Storage type of the Actor System
          jsonPath: .spec.storage.type
          name: storage
          type: string
        - description: |-
            CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.
            
                  Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
          jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    eigr_functions_protocol_major_version: '0'
    eigr_functions_protocol_minor_version: '1'
    proxy_name: spawn
    k8s-app: eigr-functions-controller
  name: eigr-functions
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - spawn.eigr.io
    resources:
      - activators
    verbs:
      - '*'
  - apiGroups:
      - spawn.eigr.io
    resources:
      - actornodes
    verbs:
      - '*'
  - apiGroups:
      - spawn.eigr.io
    resources:
      - actorsystems
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - services
      - pods
      - configmaps
    verbs:
      - '*'
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - '*'
  - apiGroups:
      - extensions
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - '*'
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - services
      - pods
      - configmaps
    verbs:
      - '*'
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - '*'
  - apiGroups:
      - extensions
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - '*'
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - services
      - pods
      - configmaps
    verbs:
      - '*'

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    eigr_functions_protocol_major_version: '0'
    eigr_functions_protocol_minor_version: '1'
    proxy_name: spawn
    k8s-app: eigr-functions-controller
  name: eigr-functions
  namespace: eigr-functions

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    eigr_functions_protocol_major_version: '0'
    eigr_functions_protocol_minor_version: '1'
    proxy_name: spawn
    k8s-app: eigr-functions-controller
  name: eigr-functions
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eigr-functions
subjects:
  - kind: ServiceAccount
    name: eigr-functions
    namespace: eigr-functions
