---
apiVersion: spawn.eigr.io/v1
kind: ActorSystem
metadata:
  name: my-actor-system # Mandatory. Name of the state store
  namespace: default # Optional. Default namespace is "default"
spec:
  storage:
    type: Postgres
    paramsSecretRef: postgres-connection-secret # The secret containing connection params
