---
apiVersion: spawn-eigr.io/v1
kind: Activator
metadata:
  name: myapp-grpc-activator
spec:
  activator:
    type: gRPC
    expose: true
    exposeMethod: ingress
    exposeHost: myactor-api.eigr.io
    grpFileDescriptorRef: protobuf-file-descriptors-secret
    port: 4000
  bindings:
    sources:
      - name: actor-action-mapping
        service: "io.eigr.spawn.example.TestService"
        typesPackage: "io.eigr.spawn.example"
        inputType: "Sum"
        outputType: "MyBusinessMessage"
    sinks:
      - name: actor-sink
        actor: "JoeActor"
        action: sum
