---
apiVersion: spawn-eigr.io/v1
kind: ActorHost
metadata:
  name: spawn-dice-game
  namespace: default
  annotations:
    spawn-eigr.io/actor-system: game-system
spec:
  host:
    image: eigr/dice-game-example:1.4.3
    embedded: true
    ports:
      - name: "http"
        containerPort: 8800
  autoscaler:
    min: 2
    max: 3
