apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-activator-settings-cm
  namespace: default
data:
  config.json: |-
    {
        "settings": {
            "actorConcurrency": 1,
            "sourceConcurrency": 1,
            "maxDemand": 2,
            "prefetchCount": 50,
            "useRateLimiting": true,
            "rateLimitingInterval": 1,
            "rateLimitingAllowedMessages": 100
        },
        "bindings": [
            {
                "name": "test-queue-config",
                "source": {
                    "queue": "test.queue"
                },
                "sinks": [
                    {
                        "name": "robert-sink",
                        "to": {
                            "actor": {
                                "type": "unnamed",
                                "action": "setLanguage",
                                "actorId": {
                                    "parent": "abs_actor",
                                    "systemFrom": {
                                        "strategy": {
                                            "type": "metadata", // or fixed
                                            "value": "app_id"
                                        },
                                        "prefixWith": "some-"
                                        "suffixWith": "-system",
                                    },
                                    "nameFrom": {
                                        "strategy": {
                                            "type": "metadata", // or fixed
                                            "value": "user_id" // valid entries are: [app_id, user_id, message_id, correlation_id, or any key present on amqp headers key]
                                        },
                                        "prefixWith": "some-"
                                        "suffixWith": "-actor",
                                    }
                                }
                            }
                        }
                    }
                ]
            }
        ]
    }
