---
apiVersion: spawn-eigr.io/v1
kind: ActorHost
metadata:
  name: spawn-springboot-example # Mandatory. Name of the Node containing Actor Host Functions
  namespace: default # Optional. Default namespace is "default"
  annotations:
    spawn-eigr.io/actor-system: spawn-system
    spawn-eigr.io/sidecar-http-port: "9001"
    spawn-eigr.io/sidecar-pubsub-adapter: "nats"
    spawn-eigr.io/sidecar-pubsub-nats-hosts: "nats://spawn-nats:4222"
    spawn-eigr.io/sidecar-image-tag: "ghcr.io/eigr/spawn-proxy:1.4.3"
spec:
  autoscaler:
    max: 3
  host:
    image: eigr/spawn-springboot-examples:0.5.3 # Mandatory
    ports:
      - name: http
        containerPort: 8090
    configuration:
      accessControlList:
        policies:
          - name: allow-all-from-same-actorsystem
            actors:
              - "*"
            type: allow
            fromActorSystems:
              - "spawn-system"
            actions:
              - "get"
              - "sum"
