---
apiVersion: spawn-eigr.io/v1
kind: ActorSystem
metadata:
  name: spawn-system # Mandatory. Name of the state store
  namespace: default # Optional. Default namespace is "default"
spec:
  cluster:
    features:
      nats:
        enabled: true
        credentialsSecretRef: "nats-invocation-conn-secret"
  statestore:
    type: MySql
    credentialsSecretRef: mysql-connection-secret # The secret containing connection params
    pool: # Optional
      size: "10"
