---
apiVersion: spawn-eigr.io/v1
kind: ActorSystem
metadata:
  name: spawn-system
  namespace: default
spec:
  cluster:
    features:
      nats:
        enabled: true
        credentialsSecretRef: "nats-invocation-conn-secret" # 3. Nats broker credentials
  statestore:
    type: MySql
    credentialsSecretRef: mysql-connection-secret
    pool:
      size: "3"
