---
apiVersion: spawn-eigr.io/v1
kind: ActorHost
metadata:
  name: topology-example # Mandatory. Name of the Node containing Actor Host Functions
  namespace: default # Optional. Default namespace is "default"
  annotations:
    # Mandatory. Name of the ActorSystem declared in ActorSystem CRD
    spawn-eigr.io/actor-system: spawn-system
spec:
  host:
    image: eigr/spawn-springboot-examples:0.5.5 # Mandatory
    topology:
      nodeSelector:
        gpu: "false"
      tolerations:
        - key: "cpu-machines"
          operator: "Exists"
          effect: "NoExecute"
      # this configure podTemplate for Task Actors
      taskActors:
        - parentName: Jose
          nodeSelector:
            gpu: "true"
          tolerations:
            - key: "gpu-machines"
              operator: "Exists"
              effect: "NoExecute"
        - parentName: Franchesco
          nodeSelector:
            beam: "true"
