---
spec:
  template:
    spec:
      containers:
        - env:
            - name: MIX_ENV
              value: prod
            - name: BONNY_OPERATOR_NAME
              value: spawn-operator
            - name: BONNY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: BONNY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: BONNY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: BONNY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          name: spawn-operator
          ports:
            - containerPort: 9090
          image: eigr/spawn-operator:1.0.0-rc.37
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 200Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /app/.cache/bakeware/
              name: bakeware-cache
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/liveness
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/readiness
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
      serviceAccountName: spawn-operator
      volumes:
        - emptyDir: {}
          name: bakeware-cache
    metadata:
      labels:
        k8s-app: spawn-operator
  selector:
    matchLabels:
      k8s-app: spawn-operator
  replicas: 1
metadata:
  name: spawn-operator
  labels:
    k8s-app: spawn-operator
  namespace: eigr-functions
kind: Deployment
apiVersion: apps/v1

---
spec:
  scope: Namespaced
  group: spawn-eigr.io
  names:
    kind: Activator
    singular: activator
    plural: activators
    shortNames:
      - act
      - acts
      - activator
      - activators
  versions:
    - name: v1
      deprecated: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
          x-kubernetes-preserve-unknown-fields: true
      storage: true
      served: true
      deprecationWarning:
      additionalPrinterColumns: []
      subresources:
        status: {}
metadata:
  name: activators.spawn-eigr.io
  labels: {}
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1

---
spec:
  scope: Namespaced
  group: spawn-eigr.io
  names:
    kind: ActorHost
    singular: actorhost
    plural: actorhosts
    shortNames:
      - ac
      - actor
      - actors
      - actorhost
      - actorhosts
  versions:
    - name: v1
      deprecated: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
          x-kubernetes-preserve-unknown-fields: true
      storage: true
      served: true
      deprecationWarning:
      additionalPrinterColumns: []
      subresources:
        status: {}
metadata:
  name: actorhosts.spawn-eigr.io
  labels: {}
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1

---
spec:
  scope: Namespaced
  group: spawn-eigr.io
  names:
    kind: ActorSystem
    singular: actorsystem
    plural: actorsystems
    shortNames:
      - as
      - actorsys
      - actorsystem
      - actorsystems
      - system
  versions:
    - name: v1
      deprecated: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
          x-kubernetes-preserve-unknown-fields: true
      storage: true
      served: true
      deprecationWarning:
      additionalPrinterColumns: []
      subresources:
        status: {}
metadata:
  name: actorsystems.spawn-eigr.io
  labels: {}
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1

---
metadata:
  name: spawn-operator
  labels:
    k8s-app: spawn-operator
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
rules:
  - resources:
      - configmaps
    verbs:
      - "*"
    apiGroups:
      - ""
  - resources:
      - node
    verbs:
      - get
      - list
    apiGroups:
      - ""
  - resources:
      - nodes
    verbs:
      - get
      - list
    apiGroups:
      - ""
  - resources:
      - pods
    verbs:
      - "*"
    apiGroups:
      - ""
  - resources:
      - secrets
    verbs:
      - "*"
    apiGroups:
      - ""
  - resources:
      - serviceaccounts
    verbs:
      - "*"
    apiGroups:
      - ""
  - resources:
      - services
    verbs:
      - "*"
    apiGroups:
      - ""
  - resources:
      - customresourcedefinitions
    verbs:
      - "*"
    apiGroups:
      - apiextensions.k8s.io
  - resources:
      - daemonsets
    verbs:
      - "*"
    apiGroups:
      - apps
  - resources:
      - deployments
    verbs:
      - "*"
    apiGroups:
      - apps
  - resources:
      - horizontalpodautoscalers
    verbs:
      - "*"
    apiGroups:
      - autoscaling
  - resources:
      - cronjob
    verbs:
      - "*"
    apiGroups:
      - batch
  - resources:
      - cronjobs
    verbs:
      - "*"
    apiGroups:
      - batch
  - resources:
      - job
    verbs:
      - "*"
    apiGroups:
      - batch
  - resources:
      - jobs
    verbs:
      - "*"
    apiGroups:
      - batch
  - resources:
      - certificate
    verbs:
      - "*"
    apiGroups:
      - cert-manager.io
  - resources:
      - leases
    verbs:
      - "*"
    apiGroups:
      - coordination.k8s.io
  - resources:
      - events
    verbs:
      - "*"
    apiGroups:
      - events.k8s.io
  - resources:
      - ingressclasses
    verbs:
      - "*"
    apiGroups:
      - extensions
  - resources:
      - ingresses
    verbs:
      - "*"
    apiGroups:
      - extensions
  - resources:
      - ingressclasses
    verbs:
      - "*"
    apiGroups:
      - networking.k8s.io
  - resources:
      - ingresses
    verbs:
      - "*"
    apiGroups:
      - networking.k8s.io
  - resources:
      - rolebindings
    verbs:
      - "*"
    apiGroups:
      - rbac.authorization.k8s.io
  - resources:
      - roles
    verbs:
      - "*"
    apiGroups:
      - rbac.authorization.k8s.io
  - resources:
      - activators
    verbs:
      - "*"
    apiGroups:
      - spawn-eigr.io
  - resources:
      - activators/status
    verbs:
      - "*"
    apiGroups:
      - spawn-eigr.io
  - resources:
      - actorhosts
    verbs:
      - "*"
    apiGroups:
      - spawn-eigr.io
  - resources:
      - actorhosts/status
    verbs:
      - "*"
    apiGroups:
      - spawn-eigr.io
  - resources:
      - actorsystems
    verbs:
      - "*"
    apiGroups:
      - spawn-eigr.io
  - resources:
      - actorsystems/status
    verbs:
      - "*"
    apiGroups:
      - spawn-eigr.io

---
metadata:
  name: spawn-operator
  labels:
    k8s-app: spawn-operator
  namespace: eigr-functions
kind: ServiceAccount
apiVersion: v1

---
metadata:
  name: spawn-operator
  labels:
    k8s-app: spawn-operator
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
roleRef:
  name: spawn-operator
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: spawn-operator
    kind: ServiceAccount
    namespace: eigr-functions
