# ---
# metadata:
#   name: spawn-operator
#   labels:
#     k8s-app: spawn-operator
#   namespace: eigr-functions
# spec:
#   template:
#     metadata:
#       labels:
#         k8s-app: spawn-operator
#     spec:
#       containers:
#         - env:
#             - name: MIX_ENV
#               value: prod
#             - name: BONNY_OPERATOR_NAME
#               value: spawn-operator
#             - name: BONNY_POD_NAME
#               valueFrom:
#                 fieldRef:
#                   fieldPath: metadata.name
#             - name: BONNY_POD_NAMESPACE
#               valueFrom:
#                 fieldRef:
#                   fieldPath: metadata.namespace
#             - name: BONNY_POD_IP
#               valueFrom:
#                 fieldRef:
#                   fieldPath: status.podIP
#             - name: BONNY_POD_SERVICE_ACCOUNT
#               valueFrom:
#                 fieldRef:
#                   fieldPath: spec.serviceAccountName
#           name: spawn-operator
#           ports:
#             - containerPort: 9090
#           image: ghcr.io/eigr/spawn-operator:2.0.0-RC4
#           resources:
#             limits:
#               cpu: 200m
#               memory: 380Mi
#             requests:
#               cpu: 200m
#               memory: 380Mi
#           securityContext:
#             runAsNonRoot: false
#             allowPrivilegeEscalation: false
#             readOnlyRootFilesystem: true
#           volumeMounts:
#             - mountPath: /app/.cache/bakeware/
#               name: bakeware-cache
#           livenessProbe:
#             failureThreshold: 3
#             httpGet:
#               path: /health/liveness
#               port: 9090
#               scheme: HTTP
#             initialDelaySeconds: 30
#             periodSeconds: 5
#             successThreshold: 1
#             timeoutSeconds: 5
#           readinessProbe:
#             failureThreshold: 3
#             httpGet:
#               path: /health/readiness
#               port: 9090
#               scheme: HTTP
#             initialDelaySeconds: 30
#             periodSeconds: 5
#             successThreshold: 1
#             timeoutSeconds: 5
#       volumes:
#         - emptyDir: {}
#           name: bakeware-cache
#       serviceAccountName: spawn-operator
#   selector:
#     matchLabels:
#       k8s-app: spawn-operator
#   replicas: 2
# kind: Deployment
# apiVersion: apps/v1

---
spec:
  scope: Cluster
  group: spawn-eigr.io
  names:
    kind: Activator
    plural: activators
    shortNames:
      - act
      - acts
    singular: activator
  versions:
    - name: v1
      deprecated: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
          x-kubernetes-preserve-unknown-fields: true
      storage: true
      additionalPrinterColumns: []
      subresources:
        status: {}
      served: true
      deprecationWarning:
metadata:
  name: activators.spawn-eigr.io
  labels: {}
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1

---
spec:
  scope: Cluster
  group: spawn-eigr.io
  names:
    kind: ActorHost
    plural: actorhosts
    shortNames:
      - ac
      - ah
      - actor
      - actors
      - hosts
    singular: actorhost
  versions:
    - name: v1
      deprecated: false
      schema:
        openAPIV3Schema:
          type: object
          description: |
            Defines an ActorHost application. Example:


            ---
            apiVersion: spawn-eigr.io/v1
            kind: ActorHost
            metadata:
              name: my-java-app
            spec:
              host:
                image: ghcr.io/eigr/spawn-springboot-examples:latest
                sdk: java
                ports:
                - containerPort: 80
          required:
            - spec
          properties:
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      message:
                        type: string
                      status:
                        type: string
                        enum:
                          - 'True'
                          - 'False'
                      type:
                        type: string
                      lastHeartbeatTime:
                        type: string
                        format: date-time
                      lastTransitionTime:
                        type: string
                        format: date-time
                observedGeneration:
                  type: integer
            spec:
              properties:
                affinity:
                  type: object
                autoscaler:
                  properties:
                    averageCpuUtilizationPercentage:
                      type: integer
                    averageMemoryUtilizationValue:
                      type: integer
                    max:
                      type: integer
                    min:
                      type: integer
                  type: object
                env:
                  items:
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                      valueFrom:
                        properties:
                          fieldRef:
                            properties:
                              fieldPath:
                                type: string
                            type: object
                        type: object
                    type: object
                  type: array
                host:
                  properties:
                    embedded:
                      type: boolean
                    image:
                      type: string
                    ports:
                      items:
                        properties:
                          containerPort:
                            type: integer
                          name:
                            type: string
                        type: object
                      type: array
                    sdk:
                      enum:
                        - dart
                        - elixir
                        - go
                        - java
                        - python
                        - rust
                        - springboot
                        - nodejs
                      type: string
                    taskActors:
                      items:
                        properties:
                          actorName:
                            type: string
                          topology:
                            properties:
                              nodeSelector:
                                additionalProperties:
                                  type: string
                                type: object
                              tolerations:
                                items:
                                  properties:
                                    effect:
                                      type: string
                                    key:
                                      type: string
                                    operator:
                                      type: string
                                  type: object
                                type: array
                            type: object
                          workerPool:
                            properties:
                              bootTimeout:
                                type: integer
                              callTimeout:
                                type: integer
                              idleShutdownAfter:
                                type: integer
                              max:
                                type: integer
                              maxConcurrency:
                                type: integer
                              min:
                                type: integer
                              oneOff:
                                enum:
                                  - 'true'
                                  - 'false'
                                type: string
                            type: object
                        type: object
                      type: array
                  required:
                    - image
                  type: object
                replicas:
                  type: integer
                topology:
                  properties:
                    nodeSelector:
                      additionalProperties:
                        type: string
                      type: object
                    tolerations:
                      items:
                        properties:
                          effect:
                            type: string
                          key:
                            type: string
                          operator:
                            type: string
                        type: object
                      type: array
                  type: object
              type: object
      storage: true
      additionalPrinterColumns:
        - name: SDK
          type: string
          description: SDK used by the ActorHost
          jsonPath: .spec.host.sdk
        - name: Embedded
          type: string
          description: Embedded Proxy used by the ActorHost
          jsonPath: .spec.host.embedded
        - name: Image
          type: string
          description: Docker image used for the ActorHost
          jsonPath: .spec.host.image
        - name: Min Replicas
          type: integer
          description: Minimum number of replicas for the ActorHost
          jsonPath: .spec.autoscaler.min
        - name: Max Replicas
          type: integer
          description: Maximum number of replicas for the ActorHost
          jsonPath: .spec.autoscaler.max
      subresources:
        status: {}
      served: true
      deprecationWarning:
metadata:
  name: actorhosts.spawn-eigr.io
  labels: {}
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1

---
spec:
  scope: Cluster
  group: spawn-eigr.io
  names:
    kind: ActorSystem
    plural: actorsystems
    shortNames:
      - as
      - actorsys
      - system
    singular: actorsystem
  versions:
    - name: v1
      deprecated: false
      schema:
        openAPIV3Schema:
          type: object
          description: Defines an Spawn ActorSystem to configure group of ActorHost applications.
          required:
            - spec
          properties:
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      message:
                        type: string
                      status:
                        type: string
                        enum:
                          - 'True'
                          - 'False'
                      type:
                        type: string
                      lastHeartbeatTime:
                        type: string
                        format: date-time
                      lastTransitionTime:
                        type: string
                        format: date-time
                observedGeneration:
                  type: integer
            spec:
              properties:
                cluster:
                  properties:
                    cookie:
                      type: string
                    kind:
                      default: erlang
                      enum:
                        - erlang
                        - quic
                      type: string
                    systemToSystem:
                      properties:
                        enabled:
                          type: boolean
                        natsClusterSecretRef:
                          type: string
                      type: object
                    tls:
                      properties:
                        certManager:
                          properties:
                            enabled:
                              type: boolean
                            issuerName:
                              type: string
                          type: object
                        secretName:
                          type: string
                      type: object
                  type: object
                statestore:
                  properties:
                    credentialsSecretRef:
                      type: string
                    pool:
                      properties:
                        size:
                          type: integer
                      type: object
                    type:
                      enum:
                        - Native
                        - native
                        - MariaDB
                        - mariadb
                        - Postgres
                        - postgres
                      type: string
                  type: object
              type: object
      storage: true
      additionalPrinterColumns:
        - name: Cluster Kind
          type: string
          description: The kind of cluster used for the ActorSystem
          jsonPath: .spec.cluster.kind
        - name: Statestore
          type: string
          description: The type of state store used for the ActorSystem
          jsonPath: .spec.statestore.type
        - name: Pool Size
          type: string
          description: The pool size of the state store
          jsonPath: .spec.statestore.pool.size
      subresources:
        status: {}
      served: true
      deprecationWarning:
metadata:
  name: actorsystems.spawn-eigr.io
  labels: {}
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1

---
metadata:
  name: spawn-operator
  labels:
    k8s-app: spawn-operator
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
rules:
  - resources:
      - configmaps
    apiGroups:
      - ""
    verbs:
      - '*'
  - resources:
      - node
    apiGroups:
      - ""
    verbs:
      - get
      - list
  - resources:
      - nodes
    apiGroups:
      - ""
    verbs:
      - get
      - list
  - resources:
      - pods
    apiGroups:
      - ""
    verbs:
      - '*'
  - resources:
      - secrets
    apiGroups:
      - ""
    verbs:
      - '*'
  - resources:
      - serviceaccount
    apiGroups:
      - ""
    verbs:
      - '*'
  - resources:
      - serviceaccounts
    apiGroups:
      - ""
    verbs:
      - '*'
  - resources:
      - services
    apiGroups:
      - ""
    verbs:
      - '*'
  - resources:
      - customresourcedefinitions
    apiGroups:
      - apiextensions.k8s.io
    verbs:
      - '*'
  - resources:
      - daemonsets
    apiGroups:
      - apps
    verbs:
      - '*'
  - resources:
      - deployments
    apiGroups:
      - apps
    verbs:
      - '*'
  - resources:
      - horizontalpodautoscalers
    apiGroups:
      - autoscaling
    verbs:
      - '*'
  - resources:
      - cronjob
    apiGroups:
      - batch
    verbs:
      - '*'
  - resources:
      - cronjobs
    apiGroups:
      - batch
    verbs:
      - '*'
  - resources:
      - job
    apiGroups:
      - batch
    verbs:
      - '*'
  - resources:
      - jobs
    apiGroups:
      - batch
    verbs:
      - '*'
  - resources:
      - certificate
    apiGroups:
      - cert-manager.io
    verbs:
      - '*'
  - resources:
      - leases
    apiGroups:
      - coordination.k8s.io
    verbs:
      - '*'
  - resources:
      - events
    apiGroups:
      - events.k8s.io
    verbs:
      - '*'
  - resources:
      - ingressclasses
    apiGroups:
      - extensions
    verbs:
      - '*'
  - resources:
      - ingresses
    apiGroups:
      - extensions
    verbs:
      - '*'
  - resources:
      - ingressclasses
    apiGroups:
      - networking.k8s.io
    verbs:
      - '*'
  - resources:
      - ingresses
    apiGroups:
      - networking.k8s.io
    verbs:
      - '*'
  - resources:
      - role
    apiGroups:
      - rbac.authorization.k8s.io
    verbs:
      - '*'
  - resources:
      - rolebindings
    apiGroups:
      - rbac.authorization.k8s.io
    verbs:
      - '*'
  - resources:
      - roles
    apiGroups:
      - rbac.authorization.k8s.io
    verbs:
      - '*'
  - resources:
      - activators
    apiGroups:
      - spawn-eigr.io
    verbs:
      - '*'
  - resources:
      - activators/status
    apiGroups:
      - spawn-eigr.io
    verbs:
      - '*'
  - resources:
      - actorhosts
    apiGroups:
      - spawn-eigr.io
    verbs:
      - '*'
  - resources:
      - actorhosts/status
    apiGroups:
      - spawn-eigr.io
    verbs:
      - '*'
  - resources:
      - actorsystems
    apiGroups:
      - spawn-eigr.io
    verbs:
      - '*'
  - resources:
      - actorsystems/status
    apiGroups:
      - spawn-eigr.io
    verbs:
      - '*'

---
metadata:
  name: spawn-operator
  labels:
    k8s-app: spawn-operator
  namespace: eigr-functions
kind: ServiceAccount
apiVersion: v1

---
metadata:
  name: spawn-operator
  labels:
    k8s-app: spawn-operator
kind: ClusterRoleBinding
subjects:
  - name: spawn-operator
    kind: ServiceAccount
    namespace: eigr-functions
apiVersion: rbac.authorization.k8s.io/v1
roleRef:
  name: spawn-operator
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
