---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: spawn-operator
  name: spawn-operator
  namespace: eigr-functions
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: spawn-operator
  template:
    metadata:
      labels:
        k8s-app: spawn-operator
    spec:
      containers:
        - env:
            - name: MIX_ENV
              value: prod
            - name: BONNY_OPERATOR_NAME
              value: spawn-operator
            - name: BONNY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: BONNY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: BONNY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: BONNY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          image: eigr/spawn-operator:1.4.2
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/liveness
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          name: spawn-operator
          ports:
            - containerPort: 9090
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/readiness
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 200m
              memory: 380Mi
            requests:
              cpu: 200m
              memory: 380Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: false
          volumeMounts:
            - mountPath: /app/.cache/bakeware/
              name: bakeware-cache
      serviceAccountName: spawn-operator
      volumes:
        - emptyDir: {}
          name: bakeware-cache

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels: {}
  name: activators.spawn-eigr.io
spec:
  group: spawn-eigr.io
  names:
    kind: Activator
    plural: activators
    shortNames:
      - act
      - acts
      - activator
      - activators
    singular: activator
  scope: Namespaced
  versions:
    - additionalPrinterColumns: []
      deprecated: false
      deprecationWarning:
      name: v1
      schema:
        openAPIV3Schema:
          properties:
            status:
              properties:
                observedGeneration:
                  type: integer
              type: object
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels: {}
  name: actorhosts.spawn-eigr.io
spec:
  group: spawn-eigr.io
  names:
    kind: ActorHost
    plural: actorhosts
    shortNames:
      - ac
      - actor
      - actors
      - actorhost
      - actorhosts
    singular: actorhost
  scope: Namespaced
  versions:
    - additionalPrinterColumns: []
      deprecated: false
      deprecationWarning:
      name: v1
      schema:
        openAPIV3Schema:
          properties:
            status:
              properties:
                observedGeneration:
                  type: integer
              type: object
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels: {}
  name: actorsystems.spawn-eigr.io
spec:
  group: spawn-eigr.io
  names:
    kind: ActorSystem
    plural: actorsystems
    shortNames:
      - as
      - actorsys
      - actorsystem
      - actorsystems
      - system
    singular: actorsystem
  scope: Namespaced
  versions:
    - additionalPrinterColumns: []
      deprecated: false
      deprecationWarning:
      name: v1
      schema:
        openAPIV3Schema:
          properties:
            status:
              properties:
                observedGeneration:
                  type: integer
              type: object
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    k8s-app: spawn-operator
  name: spawn-operator
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - node
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - serviceaccount
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - '*'
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - daemonsets
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - '*'
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - '*'
  - apiGroups:
      - batch
    resources:
      - cronjob
    verbs:
      - '*'
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - '*'
  - apiGroups:
      - batch
    resources:
      - job
    verbs:
      - '*'
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - '*'
  - apiGroups:
      - cert-manager.io
    resources:
      - certificate
    verbs:
      - '*'
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - '*'
  - apiGroups:
      - extensions
    resources:
      - ingressclasses
    verbs:
      - '*'
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - '*'
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingressclasses
    verbs:
      - '*'
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - '*'
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - role
    verbs:
      - '*'
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - '*'
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
    verbs:
      - '*'
  - apiGroups:
      - spawn-eigr.io
    resources:
      - activators
    verbs:
      - '*'
  - apiGroups:
      - spawn-eigr.io
    resources:
      - activators/status
    verbs:
      - '*'
  - apiGroups:
      - spawn-eigr.io
    resources:
      - actorhosts
    verbs:
      - '*'
  - apiGroups:
      - spawn-eigr.io
    resources:
      - actorhosts/status
    verbs:
      - '*'
  - apiGroups:
      - spawn-eigr.io
    resources:
      - actorsystems
    verbs:
      - '*'
  - apiGroups:
      - spawn-eigr.io
    resources:
      - actorsystems/status
    verbs:
      - '*'

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: spawn-operator
  name: spawn-operator
  namespace: eigr-functions

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    k8s-app: spawn-operator
  name: spawn-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spawn-operator
subjects:
  - kind: ServiceAccount
    name: spawn-operator
    namespace: eigr-functions
