---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spawn-system-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - "*"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spawn-system-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spawn-system-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spawn-system-role
subjects:
  - kind: ServiceAccount
    name: spawn-system-sa
    namespace: default
