---
apiVersion: spawn-eigr.io/v1
kind: ActorHost
metadata:
  name: spawn-springboot-example # Mandatory. Name of the Node containing Actor Host Functions
  namespace: default # Optional. Default namespace is "default"
  annotations:
    # Mandatory. Name of the ActorSystem declared in ActorSystem CRD
    spawn-eigr.io/actor-system: spawn-system

    # Optional. Default 9001
    spawn-eigr.io/sidecar-http-port: "9001"

    # Optional. Here I`m using Nats Broker without authentication
    spawn-eigr.io/sidecar-pubsub-adapter: "nats"
    spawn-eigr.io/sidecar-pubsub-nats-hosts: "nats://spawn-nats:4222"
    spawn-eigr.io/sidecar-image-tag: "ghcr.io/eigr/spawn-proxy:1.4.3"
spec:
  host:
    image: ttl.sh/spawn-java-example:24h # Mandatory
    ports:
      - name: http
        containerPort: 8090
  autoscaler:
    max: 3
