---
apiVersion: spawn-eigr.io/v1
kind: ActorSystem
metadata:
  name: spawn-system # Mandatory. Name of the state store
  namespace: default # Optional. Default namespace is "default"
spec:
  # cluster:
  #   features:
  #     nats:
  #       enabled: true
  #       credentialsSecretRef: "nats-invocation-conn-secret" # 3. Nats broker credentials
  statestore:
    type: "MariaDB"
    credentialsSecretRef: "mariadb-connection-secret" # The secret containing connection params
    pool: # Optional
      size: 10
