name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    runs-on: ubuntu-latest
    services:
      db:
        env:
          MYSQL_USER: admin
          MYSQL_PASSWORD: "admin"
          MYSQL_ROOT_PASSWORD: "admin"
          MYSQL_DATABASE: "eigr-functions-db"
        image: mysql:5.7
        ports: ["3306:3306"]
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      matrix:
        otp: [23, 24, 25]
        elixir: [1.14]

    env:
      MIX_ENV: test
      ImageOS: ubuntu20 # equivalent to runs-on ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{matrix.elixir}} # Define the elixir version [required]
          otp-version: ${{matrix.otp}} # Define the OTP version [required]

      - uses: actions/cache@v1
        id: deps-cache
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - uses: actions/cache@v1
        id: build-cache
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@master

      - name: Test cluster !
        run: kubectl get pods -A

      - name: Install dependencies
        run: |
          mix deps.clean --all
          mix deps.get

      - name: Run tests spawn
        run: |
          MIX_ENV=test PROXY_DATABASE_TYPE=mysql PROXY_CLUSTER_STRATEGY=gossip PROXY_HTTP_PORT=9005 SPAWN_STATESTORE_KEY=3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvQkPfq/XwqE= elixir --name spawn@127.0.0.1 -S mix test

      - name: Run tests spawn_sdk
        run: |
          cd spawn_sdk/spawn_sdk
          mix deps.get
          MIX_ENV=test PROXY_DATABASE_TYPE=mysql PROXY_CLUSTER_STRATEGY=gossip PROXY_HTTP_PORT=9005 SPAWN_STATESTORE_KEY=3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvQkPfq/XwqE= elixir --name spawn@127.0.0.1 -S mix test
          cd ../../

      - name: Run tests spawn_statestores
        run: |
          cd spawn_statestores/statestores_mysql
          mix deps.get
          MIX_ENV=test PROXY_CLUSTER_STRATEGY=gossip PROXY_HTTP_PORT=9005 SPAWN_STATESTORE_KEY=3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvQkPfq/XwqE= elixir --name spawn@127.0.0.1 -S mix test
          cd ../../

      - name: Run tests proxy
        run: |
          cd spawn_proxy/proxy
          mix deps.get
          MIX_ENV=test PROXY_DATABASE_TYPE=mysql PROXY_CLUSTER_STRATEGY=gossip PROXY_HTTP_PORT=9005 SPAWN_STATESTORE_KEY=3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvQkPfq/XwqE= elixir --name spawn@127.0.0.1 -S mix test
          cd ../../

      - name: Run tests operator
        run: |
          cd spawn_operator/spawn_operator
          mix deps.get
          MIX_ENV=test PROXY_DATABASE_TYPE=mysql PROXY_CLUSTER_STRATEGY=gossip PROXY_HTTP_PORT=9005 SPAWN_STATESTORE_KEY=3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvQkPfq/XwqE= elixir --name spawn@127.0.0.1 -S mix test
          cd ../../

      # - name: Run tests activator
      #   run: |
      #     cd spawn_activators/activator
      #     mix deps.get
      #     MIX_ENV=test PROXY_DATABASE_TYPE=mysql PROXY_CLUSTER_STRATEGY=gossip PROXY_HTTP_PORT=9005 SPAWN_STATESTORE_KEY=3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvQkPfq/XwqE= elixir --name spawn@127.0.0.1 -S mix test
      #     cd ../../

      # - name: Run tests activator_grpc
      #   run: |
      #     cd spawn_activators/activator_grpc
      #     mix deps.get
      #     MIX_ENV=test PROXY_DATABASE_TYPE=mysql PROXY_CLUSTER_STRATEGY=gossip PROXY_HTTP_PORT=9005 SPAWN_STATESTORE_KEY=3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvQkPfq/XwqE= elixir --name spawn@127.0.0.1 -S mix test
      #     cd ../../

      # - name: Run tests activator_http
      #   run: |
      #     cd spawn_activators/activator_grpc
      #     mix deps.get
      #     MIX_ENV=test PROXY_DATABASE_TYPE=mysql PROXY_HTTP_PORT=905 SPAWN_STATESTORE_KEY=3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvQkPfq/XwqE= elixir --name spawn@127.0.0.1 -S mix test
      #     cd ../../

      # - name: Run tests activator_kafka
      #   run: |
      #     cd spawn_activators/activator_kafka
      #     mix deps.get
      #     MIX_ENV=test PROXY_DATABASE_TYPE=mysql PROXY_CLUSTER_STRATEGY=gossip PROXY_HTTP_PORT=9005 SPAWN_STATESTORE_KEY=3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvQkPfq/XwqE= elixir --name spawn@127.0.0.1 -S mix test
      #     cd ../../

      # - name: Run tests activator_pubsub
      #   run: |
      #     cd spawn_activators/activator_pubsub
      #     mix deps.get
      #     MIX_ENV=test PROXY_DATABASE_TYPE=mysql PROXY_CLUSTER_STRATEGY=gossip PROXY_HTTP_PORT=9005 SPAWN_STATESTORE_KEY=3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvQkPfq/XwqE= elixir --name spawn@127.0.0.1 -S mix test
      #     cd ../../

      # - name: Run tests activator_rabbitmq
      #   run: |
      #     cd spawn_activators/activator_rabbitmq
      #     mix deps.get
      #     MIX_ENV=test PROXY_DATABASE_TYPE=mysql PROXY_CLUSTER_STRATEGY=gossip PROXY_HTTP_PORT=9005 SPAWN_STATESTORE_KEY=3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvQkPfq/XwqE= elixir --name spawn@127.0.0.1 -S mix test
      #     cd ../../

      # - name: Run tests activator_sqs
      #   run: |
      #     cd spawn_activators/activator_sqs
      #     mix deps.get
      #     MIX_ENV=test PROXY_DATABASE_TYPE=mysql PROXY_CLUSTER_STRATEGY=gossip PROXY_HTTP_PORT=9005 SPAWN_STATESTORE_KEY=3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvQkPfq/XwqE= elixir --name spawn@127.0.0.1 -S mix test
      #     cd ../../
